### ISSUE TITLE
Question about data handling on brainchart.io

### ISSUE THREAD

**Issue by annchenknodt** [ucam-department-of-psychiatry/Lifespan#3]
My group is excited about this work and eager to use brainchart to benchmark our data.  Since our protocol prevents us from sharing our data, I wanted to ask whether any data uploaded to brainchart.io for computation of centiles are ever stored anywhere? THanks!

**Comment by rb643** [comment]
Apologies for the slow response. The shiny dashboard effectively operates similar to a container and does not retain any data you upload, its is only held in working memory during computation but we do not have access to anything anyone else will upload. So you can safely run data through without worrying about data sharing etc. If in future you ever want to explore a DUA/MTA to add your data to the reference then do of course let us know.

Note we have switched out main repo to: https://github.com/brainchart/Lifespan
